### PR TITLE
Fix the checksum calculation in the cli command.

### PR DESCRIPTION
**Pull request by ttung**
The job of tile writing is delegated to two components: a opener, which returns a context manager that acts like a file, and a writer, which takes that file-like object and writes the data to it.

The checksum cli command works by creating a non-operational context manager, paired with a writer that does nothing.  Unfortunately, to calculate the checksum, we need to actually write to the file.

This fix changes the context manager to have a write method that does nothing, and a writer that writes the original content of the file[1].  This way, we don't write the tile files.

[1] If a tile writer is not provided, then by default, it writes the tile data as a numpy array.

### CODE REVIEW

**Comment by ambrosejcarr** [comment]
I don't understand this part: 

> The checksum cli command works by creating a non-operational context manager, paired with a writer that does nothing.  Unfortunately, to calculate the checksum, we need to actually write to the file.

**Comment by ttung** [comment]
> Specifically, why would a checksum need to write to a file?

To calculate the checksum, the library replaces the destination file handle with a [tee](https://en.wikipedia.org/wiki/Tee_(command)).  One side takes the data and writes it to the original destination file, and the second side takes the data and calculates the checksum.

slicedimage allows the caller to override the default implementations of this block of code:
```
with overridable_tile_open(dest_filename) as fh:
    overridable_write_method(tile_data, fh)
```

There are at least two ways to prevent the tile data from being written.  The old approach just makes `overridable_write_method` do nothing.  Unfortunately, it means nothing gets sent to the tee, and nothing is fed into the checksum calculation.

The new approach has `overridable_tile_open` returns a file-like object that receives the writes and drops them, but `overridable_write_method` will actually take the tile data and try to write it.

**Comment by ambrosejcarr** [comment]
Methinks some of that should be documented. However, that makes sense now. :-)

**Comment by ttung** [comment]
> Methinks some of that should be documented. However, that makes sense now. :-)

meh, not if we switch to zarr. :)

**Pull request merged**
