### PR TITLE
Add png reader/writer

### PR DESCRIPTION
**Pull request by kevinyamauchi**
This PR adds PNG reader/writer support via `imageio`.

Testing:

- [x] Add reader test
- [x] Add writer test

### CODE REVIEW

**Comment by kevinyamauchi** [comment]
@ttung , I took a crack at adding the png format. Please let me know what you think!

**Comment by ttung** [comment]
https://github.com/kevinyamauchi/slicedimage/pull/1 for your consideration.

**Comment by kevinyamauchi** [comment]
Thanks, @ttung . Removing `tifffile` makes sense to me, so I merged your commits.

**Comment by ttung** [comment]
Windows is still broken but #129 should fix that.

**Pull request merged**
